decoration:blur {
    enabled = true
    xray = true
    size = 5
    noise = 0.017
    contrast = 1
    brightness = 1
    vibrancy = 1 #0.1696
    passes = 2
    ignore_opacity = false
    new_optimizations = true

}

#layerrule = xray off, eqsh:blur
#windowrule = match:class .*, no_blur off
