################
### MONITORS ###
################

monitor=DP-2,2560x1440@165,0x0,1
monitor=HDMI-A-1,1600x900,2560x0,1,transform,1

# Trigger when the switch is toggled.
bindl = , switch:Lid Switch, exec, notify-send hey hielo
# Trigger when the switch is turning on.
bindl = , switch:on:Lid Switch, exec, notify-send closing lid
# Trigger when the switch is turning off.
bindl = , switch:off:Lid Switch, exec, notify-send opening lid
