#windowrule = match:class .*, hyprdecor:no_bar true
#windowrule = match:class kitty, hyprdecor:no_bar false
#windowrule = match:class kitty, hyprdecor:bar_color rgb(000000)

plugin {
  #hyprdecor {
  #  bar_height = 30
  #  bar_precedence_over_border = true
  #  bar_buttons_alignment = left
  #  bar_padding = 15
  #  bar_title_enabled = false
  #  bar_button_padding = 8
  #  bar_color = rgba(1e1e1eff)
  #  bar_part_of_window = true
  #  on_double_click = hyprctl dispatch fullscreen 1
  #  bar_text_size = 10
  #  hyprdecor-button = rgb(ff5f56), 15,, hyprctl dispatch killactive
  #  hyprdecor-button = rgb(ffbd2e), 15,, hyprctl dispatch minimize
  #  hyprdecor-button = rgb(27c93f), 15,, hyprctl dispatch fullscreen 1
  #}
  dynamic-cursors {
      enabled = true
      mode = shake
  	  threshold = 2
      shake {
          enabled = true
          nearest = true
          threshold = 6.0
          base = 3.0
          speed = 2.0
          influence = 0.0
          limit = 4.0
          timeout = 1500
  		  effects = false
      }
      hyprcursor {
          nearest = 2
          enabled = true
          resolution = -1
          fallback = clientside
      }
   }
   liquid-glass {
       enabled = true
       blur_strength = 1.0
       refraction_strength = 0.04
       chromatic_aberration = 0.004
       fresnel_strength = 1.0
       specular_strength = 0.0
       glass_opacity = 1.0
       red_tint = 0.2
       blue_tint = 0.2
       green_tint = 0.2
       edge_thickness = 0.15
   }
}


