##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = match:class org.gnome.NautilusPreviewer, float on
windowrule = match:class kitty, opacity 0.95
